[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.1",
    "pydub>=0.25.1",
    "scipy>=1.16.0",
    "speechrecognition>=3.14.3",
    "streamlit>=1.46.1",
]
